version: '3.3'

services:
  doc-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-system
    ports:
      - "38080:80"
    restart: unless-stopped
    networks:
      - doc-network

networks:
  doc-network:
    driver: bridge
